name: Deploy to Apache Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GITHUB_WORKSPACE
        run: echo "GITHUB_WORKSPACE=$PWD" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Save GITHUB_WORKSPACE path
        run: echo $GITHUB_WORKSPACE > workspace_path.txt
      
      - name: Deploy to Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APACHE_HOST }}
          username: ${{ secrets.APACHE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.APACHE_SSH_PORT }}
          script: |
            WORKSPACE_PATH=$(<workspace_path.txt)
            echo "Attempting to rsync $WORKSPACE_PATH/client/dist/ to /var/www/html/"
            rsync -av --delete $WORKSPACE_PATH/client/dist/ /var/www/html/


