name: Deploy to Apache Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Verify dist directory
        run: |
          ls -lah client/dist

      - name: Echo dist path and workspace
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Dist path: $GITHUB_WORKSPACE/client/dist/"

      - name: Deploy to Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APACHE_HOST }}
          username: ${{ secrets.APACHE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.APACHE_SSH_PORT }}
          script:  |
              echo "GITHUB_WORKSPACE is set to $GITHUB_WORKSPACE"
              echo "Attempting to rsync $GITHUB_WORKSPACE/client/dist/ to /var/www/html/"
              rsync -av --delete $GITHUB_WORKSPACE/client/dist/ /var/www/html/

